### ISSUE TITLE
Crash after updating my MPD database

### ISSUE THREAD

**Issue by be-neth** [gateship-one/malp#47]
Hi,

First of all thanks for this app.

I have a recurrent crash after updating my MPD database, with fdroid version : 1.1.4.

Log :

~~~~
03-31 18:45:16.218 13396 13470 E AndroidRuntime: Process: org.gateshipone.malp, PID: 13396
03-31 18:45:16.218 13396 13470 E AndroidRuntime: java.lang.IllegalArgumentException: Comparison method violates its general contract!
03-31 18:45:16.218 13396 13470 E AndroidRuntime:        at java.util.ComparableTimSort.mergeLo(ComparableTimSort.java:740)
03-31 18:45:16.218 13396 13470 E AndroidRuntime:        at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:477)
03-31 18:45:16.218 13396 13470 E AndroidRuntime:        at java.util.ComparableTimSort.mergeForceCollapse(ComparableTimSort.java:418)
03-31 18:45:16.218 13396 13470 E AndroidRuntime:        at java.util.ComparableTimSort.sort(ComparableTimSort.java:218)
03-31 18:45:16.218 13396 13470 E AndroidRuntime:        at java.util.Arrays.sort(Arrays.java:1325)
03-31 18:45:16.218 13396 13470 E AndroidRuntime:        at java.util.Collections.sort(Collections.java:169)
03-31 18:45:16.218 13396 13470 E AndroidRuntime:        at org.gateshipone.malp.mpdservice.mpdprotocol.MPDConnection.parseMPDArtists(MPDConnection.java:864)
03-31 18:45:16.218 13396 13470 E AndroidRuntime:        at org.gateshipone.malp.mpdservice.mpdprotocol.MPDConnection.getAlbumArtists(MPDConnection.java:1188)
03-31 18:45:16.218 13396 13470 E AndroidRuntime:        at org.gateshipone.malp.mpdservice.handlers.serverhandler.MPDQueryHandler.handleMessage(MPDQueryHandler.java:201)
03-31 18:45:16.218 13396 13470 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
03-31 18:45:16.218 13396 13470 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
03-31 18:45:16.218 13396 13470 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:61)
03-31 18:45:16.220  2855  4468 W ActivityManager:   Force finishing activity org.gateshipone.malp/.application.activities.MainActivity
~~~~

**Comment by djselbeck** [comment]
> First of all thanks for this app.

You're very welcome.

Thanks for reporting this and also providing a backtrace. I'll try to fix it.

**Comment by be-neth** [comment]
The bug does not happen anymore.
But I have updated my music library but I don't know what resolve this.

Two things I remember :
* Triggered only when : "Use Album Artist" option is enabled
* When two distinct tag "Album Artist" and "album artist" are present (Which is wrong, I know...)

**Comment by djselbeck** [comment]
Thanks ;) If I remember correctly it may have been fixed by commit f5ba7636935a62e491d09b18b4ab380f771f51f5

**Comment by djselbeck** [comment]
Closing this, if it is still an issue please reopen the issue.

**Comment by fabsmusicjunkie** [comment]
I still have this issue. Using version 1.1.8
