### ISSUE TITLE
FC in Artist View

### ISSUE THREAD

**Issue by derede** [gateship-one/malp#96]
Changing to the Artist Tab in Libary closes M.A.L.P.:
Logcat:
###########--------- beginning of main
01-24 18:28:45.746 30627 32607 W WebSocketConnection: Sending keep alive...
01-24 18:28:45.958 30627 32604 W WebSocketConnection: WSC onMessage()
01-24 18:28:45.958 30627 32604 W WebSocketConnection: Message Type: 2
01-24 18:28:53.907   324   524 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
01-24 18:28:53.910   324   524 D audio_hw_primary: start_output_stream: enter: stream(0xb6244240)usecase(1: low-latency-playback) devices(0x2)
01-24 18:28:53.910   324   524 D audio_hw_primary: select_devices: out_snd_device(2: speaker) in_snd_device(0: )
01-24 18:28:53.910   324   524 I msm8960_platform: platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(15)
01-24 18:28:53.910   324   524 D ACDB-LOADER: ACDB -> send_audio_cal, acdb_id = 15, path =  0
01-24 18:28:53.910   324   524 D ACDB-LOADER: ACDB -> send_adm_topology
01-24 18:28:53.911   324   524 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
01-24 18:28:53.911   324   524 D ACDB-LOADER: ACDB -> send_asm_topology
01-24 18:28:53.911   324   524 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
01-24 18:28:53.911   324   524 D ACDB-LOADER: ACDB -> send_audtable
01-24 18:28:53.911   324   524 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
01-24 18:28:53.911   324   524 D ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_CAL
01-24 18:28:53.911   324   524 D ACDB-LOADER: ACDB -> send_audvoltable
01-24 18:28:53.911   324   524 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_VOLTBL_STEP_COPP
01-24 18:28:53.911   324   524 E ACDB-LOADER: Error: ACDB AudProc vol returned = -8
01-24 18:28:53.911   324   524 D ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
01-24 18:28:53.911   324   524 D ACDB-LOADER: ACDB -> send_afe_cal
01-24 18:28:53.911   324   524 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
01-24 18:28:53.911   324   524 D ACDB-LOADER: ACDB -> AUDIO_SET_AFE_CAL
01-24 18:28:53.911   324   524 D ACDB-LOADER: ACDB -> send_hw_delay : acdb_id = 15 path = 0
01-24 18:28:53.911   324   524 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_DEVICE_PROPERTY_SIZE
01-24 18:28:53.911   324   524 D ACDB-LOADER: ACDB -> ACDB_AVSYNC_INFO: ACDB_CMD_GET_DEVICE_PROPERTY
01-24 18:28:53.911   324   524 D ACDB-LOADER: send_hw_delay id = 15 delay_num_entries = 1 result = 0
01-24 18:28:53.926   324   524 D audio_hw_primary: select_devices: done
01-24 18:28:54.635  1283  1498 D WifiStateMachine: updateCapabilities for config:testWlanfalse,false
01-24 18:28:55.172   324   524 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
01-24 18:28:57.673  1283  1498 D WifiStateMachine: updateCapabilities for config:testWlanfalse,false
01-24 18:28:57.930  1283  1493 D SntpClient: request time failed: java.io.IOException: Operation not permitted
01-24 18:28:57.964  1283  1493 W ConnectivityExtension: ConnectivityExt jar file not present
01-24 18:28:58.002  1283  1495 D SntpClient: request time failed: java.io.IOException: Operation not permitted
01-24 18:28:58.305   324   524 D audio_hw_primary: out_standby: enter: stream (0xb6244240) usecase(1: low-latency-playback)
01-24 18:28:58.423  6946  7583 W art     : Long monitor contention with owner AndroMPD-QueryHandler (6970) at java.util.List org.gateshipone.malp.mpdservice.mpdprotocol.MPDConnection.getArtists()(MPDConnection.java:1207) waiters=0 in org.gateshipone.malp.mpdservice.mpdprotocol.mpdobjects.MPDCurrentStatus org.gateshipone.malp.mpdservice.mpdprotocol.MPDConnection.getCurrentServerStatus() for 3.144s
--------- beginning of crash
01-24 18:28:58.425  6946  6970 E AndroidRuntime: FATAL EXCEPTION: AndroMPD-QueryHandler
01-24 18:28:58.425  6946  6970 E AndroidRuntime: Process: org.gateshipone.malp, PID: 6946
01-24 18:28:58.425  6946  6970 E AndroidRuntime: java.lang.IllegalArgumentException: Comparison method violates its general contract!
01-24 18:28:58.425  6946  6970 E AndroidRuntime:        at java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:862)
01-24 18:28:58.425  6946  6970 E AndroidRuntime:        at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:479)
01-24 18:28:58.425  6946  6970 E AndroidRuntime:        at java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:400)
01-24 18:28:58.425  6946  6970 E AndroidRuntime:        at java.util.ComparableTimSort.sort(ComparableTimSort.java:209)
01-24 18:28:58.425  6946  6970 E AndroidRuntime:        at java.util.Arrays.sort(Arrays.java:1325)
01-24 18:28:58.425  6946  6970 E AndroidRuntime:        at java.util.Collections.sort(Collections.java:169)
01-24 18:28:58.425  6946  6970 E AndroidRuntime:        at org.gateshipone.malp.mpdservice.mpdprotocol.MPDConnection.parseMPDArtists(MPDConnection.java:904)
01-24 18:28:58.425  6946  6970 E AndroidRuntime:        at org.gateshipone.malp.mpdservice.mpdprotocol.MPDConnection.getArtists(MPDConnection.java:1210)
01-24 18:28:58.425  6946  6970 E AndroidRuntime:        at org.gateshipone.malp.mpdservice.handlers.serverhandler.MPDQueryHandler.handleMessage(MPDQueryHandler.java:185)
01-24 18:28:58.425  6946  6970 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
01-24 18:28:58.425  6946  6970 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
01-24 18:28:58.425  6946  6970 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:61)
--------- beginning of system
01-24 18:28:58.428  1283  2384 W ActivityManager:   Force finishing activity org.gateshipone.malp/.application.activities.MainActivity
01-24 18:28:58.452  6946  6946 V ConnectionManager: Delayed disconnect started
01-24 18:28:58.514  4799  4799 V BackgroundService: MALP background service destroyed
01-24 18:28:58.618  1283 11292 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8974_LA.BF.1.1.3_RB1__release_AU (I741a3d36ca)
01-24 18:28:58.618  1283 11292 I Adreno-EGL: OpenGL ES Shader Compiler Version: E031.29.00.00
01-24 18:28:58.618  1283 11292 I Adreno-EGL: Build Date: 04/04/16 Mon
01-24 18:28:58.618  1283 11292 I Adreno-EGL: Local Branch: mybranch19053788
01-24 18:28:58.618  1283 11292 I Adreno-EGL: Remote Branch: quic/LA.BF.1.1.3_rb1.12
01-24 18:28:58.618  1283 11292 I Adreno-EGL: Local Patches: NONE
01-24 18:28:58.618  1283 11292 I Adreno-EGL: Reconstruct Branch: NOTHING
01-24 18:28:58.618  1283 11292 I OpenGLRenderer: Initialized EGL, version 1.4
01-24 18:28:58.619  1283 11292 D OpenGLRenderer: Swap behavior 1
01-24 18:28:58.719  1283  1296 I art     : Background partial concurrent mark sweep GC freed 27749(1671KB) AllocSpace objects, 0(0B) LOS objects, 33% free, 23MB/35MB, paused 3.845ms total 225.494ms
01-24 18:28:58.976  6946  7686 V ConnectionManager: Disconnecting from server
01-24 18:28:58.980  4799  4799 V BackgroundService: onStartCommand: org.gateshipone.malp.widget.connect
01-24 18:28:58.980  4799  4799 V BackgroundService: Action: org.gateshipone.malp.widget.connect
01-24 18:28:59.056  4799  4799 V BackgroundService: onStartCommand: org.gateshipone.malp.notification.show
01-24 18:28:59.056  4799  4799 V BackgroundService: Action: org.gateshipone.malp.notification.show
01-24 18:28:59.306  1564  1564 D ro      : inflating media notification
01-24 18:28:59.492  1283  1296 I art     : Background partial concurrent mark sweep GC freed 8942(475KB) AllocSpace objects, 0(0B) LOS objects, 33% free, 23MB/35MB, paused 4.028ms total 303.619ms
01-24 18:28:59.611  1564  1587 I art     : Background partial concurrent mark sweep GC freed 22494(1411KB) AllocSpace objects, 0(0B) LOS objects, 33% free, 31MB/47MB, paused 1.800ms total 281.707ms
01-24 18:29:00.724  1283  1498 D WifiStateMachine: updateCapabilities for config:testWlanfalse,false

**Comment by djselbeck** [comment]
Thanks for providing the logcat

**Comment by djselbeck** [comment]
Hello,

if you don't mind you can try the APK linked here. But BE AWARE, this is based on the cleaned up MPDConnection code base and might (although unlikely) some other instabilities. 

[APK](https://owncloud.djselbeck.de/index.php/s/oJ7NRlWpNFjgYUY)

**Comment by derede** [comment]
Hey Hendrik,
works like a charme, thanks!

Best regards,
Sebastian

#####
Couldn't resist, sorry...:

Some features which could be useful, what do you think...?
- sleeping timer..? 
https://github.com/AberDerBart/mpdScheduler/blob/master/README.md

- pause while calling..?
- dowload buttom for audio files..?

Am 24. Januar 2018 19:26:57 MEZ schrieb Hendrik Borghorst <notifications@github.com>:
>Hello,
>
>if you don't mind you can try the APK linked here. But BE AWARE, this
>is based on the cleaned up MPDConnection code base and might (although
>unlikely) some other instabilities. 
>
>[APK](https://owncloud.djselbeck.de/index.php/s/oJ7NRlWpNFjgYUY)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gateship-one/malp/issues/96#issuecomment-360228164

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
